### ISSUE TITLE
Question: Differences MLX90393 Series

### ISSUE THREAD

**Issue by Nivek92** [raunaqbhirangi/reskin_sensor#1]
Hey, it's less of an issue but a question. 

I was wondering why you the BOM contains 4 MLX90393ELW-ABA-011-SP and 1 MLX90393ELW-ABA-012-SP.

I coudn't find any information about the differences between the MLX90393ELW-ABA-011-SP, MLX90393ELW-ABA-012-SP, MLX90393ELW-ABA-013-SP or MLX90393ELW-ABA-014-SP.

Could you ellaborate?

**Comment by tesshellebrekers** [comment]
The chip is essentially the same, but the internal I2C address can be changed depending on which version you use (011, 012, 013, or 014). Based on the datasheet page 5 (table 1):

 ABA-011   Address = 00011xx
 ABA-012   Address = 00100xx
 ABA-013   Address = 00101xx
 ABA-014   Address = 00110xx

where xx is controlled by two pins A0 and A1. 

By using two different part numbers, we can put all five chips onto one I2C bus and use a 4-wire connection.
