### ISSUE TITLE
Ordering a circuit

### ISSUE THREAD

**Issue by mohamedamrali1993** [raunaqbhirangi/reskin_sensor#3]
Hi, I am trying to order the circuit from PCBway. I followed directions but in the "Finished Copper" section under flexible PCBs, it only allows 0.5 oz cu (18um), while directions suggest 1 oz cu (35um). Hope this is just a typo, otherwise, if it does affect the build, would you please advise.

Also, where can I get the soft magnetic skin (described as "magnetic microparticles in an elastomer matrix")? Do I have to make it in-house or can I buy it?

**Comment by tesshellebrekers** [comment]
Hi,

Can you double-check what FPC thickness you selected? With 0.1mm thickness, you can select either 0.5 oz cu or 1 oz cu. However, if you select 0.08mm thickness only 0.5 oz cu is available.

All of these options will result in a functional circuit, however, the less copper you use the more fragile the flexible PCB will be.

**Comment by tesshellebrekers** [comment]
The magnetic skin is not currently available for purchase, but there are instructions for making it on the website, reskin.dev

**Comment by mohamedamrali1993** [comment]
I had trouble recreating the situation where it only gave me a finished copper of 0.5 oz Cu, but I finally got it; you're right 0.08 mm will give 0.5 oz Cu only, but so did 0.1mm. It did give me the option of 1 oz Cu for FPC of 0.13 mm. I am ok with a 0.03 mm increase as long it doesn't affect the signal. Thanks so much for your help.
